apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: php
        image: nextcloud:fpm
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-data
        hostPath:
          path: /mnt/nextcloud
          type: Directory
      - name: nginx-config
        configMap:
          name: nginx-config
